<?php

namespace app\api\modules\v1\models;

class Yangilik extends \app\models\Product {
    public function fields()
    {
        return [
            'nomi' => 'name',
            'soni' => function ($model){
                return floor($model->quantity);
            },
            'brend' => function ($model) {
                return $model->brand->name;
            }
        ];
    }
    public function extraFields()
    {
        return [
            'measurement' => function ($model){
                return $model->measurement;
            }
        ]; // TODO: Change the autogenerated stub
    }
}