<?php

    namespace app\models;

    use phpDocumentor\Reflection\Types\Null_;
    use Yii;
    use yii\base\Model;
    use yii\helpers\ArrayHelper;

    class ReceiveForm extends Model
    {
        public $contragent;
        public $product;
        public $receiver;
        public $quantity;
        public $price;
        public $date;
        public $sum;

        public function rules()
        {
            return [
                [['contragent', 'product', 'date', 'sum', 'quantity', 'price'], 'required'],
                ['date', 'date'],
                [['product', 'receiver', 'details', 'contragent'], 'integer'],
                [['price', 'quantity', 'sum'], 'number']
            ]; // TODO: Change the autogenerated stub
        }
        public function load($data, $formName = null)
        {
            return parent::load($data, $formName); // TODO: Change the autogenerated stub
        }

        public function getContragent(){
            return Contragent::find()->asArray()->all();
        }
        public function getProducts(){

        }
        static function getModelAsArray($model, $arrayIndex = 'id', $arrayValue = 'name', $options = []){
            if(!empty($options)):
                return ArrayHelper::map($model::find()->where($options)->asArray()->all(), $arrayIndex, $arrayValue);
            else:
                return ArrayHelper::map($model::find()->asArray()->all(), $arrayIndex, $arrayValue);
            endif;
        }

        public function attributeLabels()
        {
            return [
                'contragent' => 'Kontragentni tanlang:',
                'product' => 'Maxsulotni tanlang:',
                'price' => 'Narxi:',
                'quantity' => 'Miqdori:',
                'sum' => 'Berilgan pul:'
            ]; // TODO: Change the autogenerated stub
        }

        public static function getHammasi($id=null){
            $sql = "SELECT * FROM product WHERE id <> %d";
            return Yii::$app->db->createCommand(sprintf($sql, $id))->queryAll();
        }
    }